---

# conda -v env update --file environment.yml

name: appdaemon

channels:
- conda-forge
- defaults

dependencies:
- python=3.12.12
- astral
- pip
- pip:
  - appdaemon

# for development
- pipdeptree
- pre-commit
- black
- isort
- types-pytz
